server:
    port: 8080
spring:
    application:
        name: customer
    datasource:
        username: customer
        password: customer
        url: jdbc:postgresql://localhost:5432/customer
    jpa:
        hibernate:
            ddl-auto: create-drop
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true