version: '3'

services:
  customer-db:
    build:
      dockerfile: Dockerfile
      context: database
    image: customer-db
    container_name: customer-db
    restart: always
    ports:
      - "5432:5432"